name: Build Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t dyalog-jupyter

    - name: Build Jupyter Book
      run: |
        # No need to start container separately since we have an entrypoint
        docker run -v $(pwd):/home/dyalog/contents dyalog-jupyter
        
    - name: Upload HTML Book
      uses: actions/upload-artifact@v2
      with:
        name: book-html
        path: _build/html
        
    - name: Deploy to GitHub Pages
      if: success() # Only deploy if build succeeds
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html