name: Build Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t jupyterbook

    - name: Run Docker container
      run: |
        docker run -d --name jupyterbook jupyterbook tail -f /dev/null
        
    - name: Build Jupyter Book in Docker container
      run: |
        docker exec jupyterbook /bin/bash -c "cd /home/dyalog/contents && jupyter-book build ."

    - name: Copy built Jupyter Book from Docker container
      run: |
        docker cp jupyterbook:/home/dyalog/contents/_build ./_build
     
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-book
        path: ./_build
        
    - name: Stop Docker container
      run: |
        docker stop jupyterbook

